pip3 install tkinter
pip3 install pandas
pip3 install bs4
pip3 install xlsxwriter
pip3 install numpy
pip3 install sklearn
pip3 install seaborn
pip3 install matplotlib
pip3 install cv2
pip3 install sqlite3
pip3 install PIL
pip3 install mysql.connector
pip3 install pymysql
pip3 install imutils
pip3 install time
pip3 install datetime
pip3 install openpyxl
pip3 install pyttsx3
pip3 install tensorflow
pip3 install keras
pip3 install mediapipe